# NUMPY

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
b = np.array([[3,4,5],[3,4,5]])

In [ ]:
c = np.array([[[3,4,5],[3,4,5],[4,5,6]],[[3,4,5],[3,4,5],[4,5,6]]])

In [ ]:
print(a)

[1 2 3]


In [ ]:
print(b)

[[3 4 5]
 [3 4 5]]


In [ ]:
print(c)

[[[3 4 5]
  [3 4 5]
  [4 5 6]]

 [[3 4 5]
  [3 4 5]
  [4 5 6]]]


# INITIAL PLACEHOLDERS

In [ ]:
# create an array of zeros:

In [ ]:
np.zeros ((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# create an array of ones:

In [ ]:
np.ones ((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
# create an array of evenly spaced values:

In [ ]:
d = np.arange (1,13,3)
print(d)

[ 1  4  7 10]


In [ ]:
# create an array of evenly spaced values:

In [ ]:
np.linspace (1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [ ]:
# create a constant array: create a 1D array

In [ ]:
e = np.full ((4),7,)
print(e)
print("dim",e.ndim)

[7 7 7 7]
dim 1


In [ ]:
# create a 2D array

In [ ]:
e = np.full((3,4),3)
print(e)
print("dim",e.ndim)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
dim 2


In [ ]:
# create a 3D array

In [ ]:
e = np.full ((4,3,5),7)
print(e)
print("dim",e.ndim)

[[[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]

 [[7 7 7 7 7]
  [7 7 7 7 7]
  [7 7 7 7 7]]]
dim 3


In [ ]:
# create a 2x2 identity matrix

In [ ]:
f = np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# create an array with random values:

In [ ]:
np.random.random ((2,3))

array([[0.33601673, 0.56504174, 0.41413284],
       [0.67726124, 0.89085536, 0.03978015]])

In [ ]:
np.random.randint(2,13)

12

In [ ]:
# to find shape of an array:

In [ ]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,18],
                [1,2,3,4,5],
                [3,4,5,6,7]])
print(arr.shape)

(4, 5)


In [ ]:
# to find no of elelments in array:

In [ ]:
arr = np.array([[1,2,3,4,5],
                [3,4,5,6,7],
                [5,6,7,8,9],
                [1,2,3,4,5]])
print(arr.size)

20


In [ ]:
# to find the length of array:

In [ ]:
arr = np.array([[1,2,3,4,5],
                [3,4,5,6,7],
                [7,6,5,4,3],
                [4,5,6,7,8],
                [9,8,7,6,5]])
len(arr)

5